-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 13:41:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jobs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jobs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `benefits` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_requirement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_requirement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `jobs_id` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_id`),
  INDEX `jobs_id_idx` (`jobs_id` ASC),
  INDEX `fk_job_requirement_skill1_idx` (`skill_id` ASC),
  CONSTRAINT `FK_job_requirement-job`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `mydb`.`jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_job_requirement_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `user_roles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users-user_roles_idx` (`user_roles_id` ASC),
  CONSTRAINT `FK_users-user_roles`
    FOREIGN KEY (`user_roles_id`)
    REFERENCES `mydb`.`user_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`personal_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personal_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personal_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_info_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_personal_info_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_education` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_education` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `school_name` VARCHAR(45) NULL DEFAULT NULL,
  `graduated_year` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_education-personal-info_idx` (`personal_info_id` ASC),
  CONSTRAINT `FK_user_education-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `mydb`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_skill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skill_id`),
  INDEX `FK_user_skill-personal-info_idx` (`personal_info_id` ASC),
  INDEX `fk_user_skill_skill1_idx` (`skill_id` ASC),
  CONSTRAINT `FK_user_skill-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `mydb`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_skill_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_work_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_work_experience` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_work_experience` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `company_name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_work_experience-personal-info_idx` (`personal_info_id` ASC),
  CONSTRAINT `FK_user_work_experience-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `mydb`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
