-- MySQL Script generated by MySQL Workbench
-- Wed Aug 30 19:38:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_ROLES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `USER_ROLES_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USERS_USER_ROLES_idx` (`USER_ROLES_ID` ASC),
  CONSTRAINT `fk_USERS_USER_ROLES`
    FOREIGN KEY (`USER_ROLES_ID`)
    REFERENCES `mydb`.`USER_ROLES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONAL_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PERSONAL_INFO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PERSONAL_INFO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `USERS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PERSONAL_INFO_USERS1_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_PERSONAL_INFO_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `mydb`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_WORK_EXPERIENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_WORK_EXPERIENCE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_WORK_EXPERIENCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` VARCHAR(45) NOT NULL,
  `POSITION` VARCHAR(45) NOT NULL,
  `PERSONAL_INFO_ID` INT NOT NULL,
  `START_DATE` DATETIME NULL,
  `END_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_WORK_EXPERIENCE_PERSONAL_INFO1_idx` (`PERSONAL_INFO_ID` ASC),
  CONSTRAINT `fk_USER_WORK_EXPERIENCE_PERSONAL_INFO1`
    FOREIGN KEY (`PERSONAL_INFO_ID`)
    REFERENCES `mydb`.`PERSONAL_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SKILLS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SKILLS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SKILLS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_SKILLS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_SKILLS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_SKILLS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PERSONAL_INFO_ID` INT NOT NULL,
  `SKILL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_SKILLS_PERSONAL_INFO1_idx` (`PERSONAL_INFO_ID` ASC),
  INDEX `fk_USER_SKILLS_SKILL1_idx` (`SKILL_ID` ASC),
  CONSTRAINT `fk_USER_SKILLS_PERSONAL_INFO1`
    FOREIGN KEY (`PERSONAL_INFO_ID`)
    REFERENCES `mydb`.`PERSONAL_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_SKILLS_SKILL1`
    FOREIGN KEY (`SKILL_ID`)
    REFERENCES `mydb`.`SKILLS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_EDUCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_EDUCATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_EDUCATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SCHOOL_NAME` VARCHAR(45) NOT NULL,
  `GRADUATED_YEAR` DATETIME NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `PERSONAL_INFO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_EDUCATION_PERSONAL_INFO1_idx` (`PERSONAL_INFO_ID` ASC),
  CONSTRAINT `fk_USER_EDUCATION_PERSONAL_INFO1`
    FOREIGN KEY (`PERSONAL_INFO_ID`)
    REFERENCES `mydb`.`PERSONAL_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOBS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOBS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOBS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `BENEFITS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOB_REQUIREMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOB_REQUIREMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOB_REQUIREMENT` (
  `JOBS_ID` INT NOT NULL,
  `skill_id` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  INDEX `fk_JOBS_has_SKILL_SKILL1_idx` (`skill_id` ASC),
  INDEX `fk_JOBS_has_SKILL_JOBS1_idx` (`JOBS_ID` ASC),
  CONSTRAINT `fk_JOBS_has_SKILL_JOBS1`
    FOREIGN KEY (`JOBS_ID`)
    REFERENCES `mydb`.`JOBS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_JOBS_has_SKILL_SKILL1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`SKILLS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOB_APPLIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JOB_APPLIES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JOB_APPLIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERS_ID` INT NOT NULL,
  `JOBS_ID` INT NOT NULL,
  INDEX `fk_USERS_has_JOBS_JOBS1_idx` (`JOBS_ID` ASC),
  INDEX `fk_USERS_has_JOBS_USERS1_idx` (`USERS_ID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_USERS_has_JOBS_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `mydb`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_JOBS_JOBS1`
    FOREIGN KEY (`JOBS_ID`)
    REFERENCES `mydb`.`JOBS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
